---
swagger: "2.0"
info:
  version: '1.00'
  title: "serverless-code-dev"
host: "zlfmg2s8n4.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /channelDelete:
    delete:
      summary: delete one channel
      description: delete one channel by channedId
      parameters:
        - name: channelId
          in: query
          type: string
      responses: 
        200:
          description: success
          schema: 
            items:
              properties:
                result: 
                  type: string
        400:
          description: fail
          schema: 
            items:
              properties:
                result: 
                  type: string
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /channelInsert:
    post:
      summary: add channel 
      description: add one channel 
      parameters:
        - name: channelBody
          in: body
          schema:
            properties:
              channelBody:
                $ref: "#/definitions/Channel"
      responses: 
        200:
          description: success
          schema: 
            items:
              properties:
                result: 
                  type: string
        400:
          description: fail
          schema: 
            items:
              properties:
                result: 
                  type: string
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /channelUpdate:
    put:
      summary: update channel
      description: update one channel
      parameters:
        - name: channelBody
          in: body
          schema:
            properties:
              channelBody:
                $ref: "#/definitions/Channel"
      responses: 
        200:
          description: success
          schema: 
            items:
              properties:
                result: 
                  type: string
        400:
          description: fail
          schema: 
            items:
              properties:
                result: 
                  type: string
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /channelsGetByPage:
    get:
      summary: delete user
      description: delete user body to databse
      parameters:
        - name: sortType
          in: query
          type: string
        - name: sortAscend
          in: query
          type: boolean
        - name: page
          in: query
          type: number 
        - name: pageSize
          in: query
          type: number
      responses: 
        200:
          description: success
          schema:
            items:
                properties:
                  channels:
                    $ref: "#/definitions/Channel"
                  count:
                    type: number
        400:
          description: fail
          schema: 
            items:
              properties:
                result: 
                  type: string
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /channelsGetBySearch:
    get:
      summary: delete user
      description: delete user body to databse
      responses: 
        200:
          description: success
          schema:
            items:
              $ref: "#/definitions/Channel"
        400:
          description: fail
          schema: 
            items:
              properties:
                result: 
                  type: string
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Channel:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      message: 
        type: array
        items:
          type: object
  Message:
    type: object
    properties:
      _id:
        type: string
      channelId:
        type: string
      createAt:
        type: number
      title:
        type: string
      context:
        type: string